### ISSUE TITLE
undefined name 'MulticoreTSNE' in benchmark_tsne.py

### ISSUE THREAD

**Issue by cclauss** [pavlin-policar/fastTSNE#4]
Line 11 is commented out so __MulticoreTSNE__ is an undefined name.

[flake8](http://flake8.pycqa.org) testing of https://github.com/pavlin-policar/fastTSNE on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./benchmarks/benchmark_tsne.py:196:17: F821 undefined name 'MulticoreTSNE'
    embedding = MulticoreTSNE(
                ^
1     F821 undefined name 'MulticoreTSNE'
1
```

**Comment by pavlin-policar** [comment]
Yes, the `benchmarks` directory is a mess, this is where I do most of my testing and experimenting. However, it is excluded from any imports and does not impact the usability of the library at all. So if you want to use this library, this really shouldn't be an issue.
